### ISSUE TITLE
Leveraged & Vault Token Chart: Update gradient color

### ISSUE THREAD

**Issue by pyk** [risedle/interface#105]
Green
- Stroke: #18794E
- Background: `linear-gradient(180deg, rgba(37, 208, 171, 0.4) 0%, rgba(37, 208, 171, 0) 100%)`
- Opacity: 20%

Red: 
- TBD

**Comment by ayikfour** [comment]
Color specs for chart:

## Dark mode
Profit (green):
- Stroke: #4CC38A
- Background: `background: linear-gradient(180deg, rgba(37, 208, 171, 0.4) 0%, rgba(37, 208, 171, 0) 100%)`
- BackgroundOpacity: 40%

Loss (red):
- Stroke: #FF6369
- Background: `background: linear-gradient(180deg, rgba(255, 99, 105, 0.4) 0%, rgba(255, 99, 105, 0) 100%)`
- BackgroundOpacity: 40%

## Light mode
Profit (green):
- Stroke: #18794E
- Background: `background: linear-gradient(180deg, rgba(37, 208, 171, 0.4) 0%, rgba(37, 208, 171, 0) 100%)`
- BackgroundOpacity: 20%

Loss (red):
- Stroke: #CD2B31
- Background: `background: linear-gradient(180deg, rgba(205, 43, 49, 0.4) 0%, rgba(205, 43, 49, 0) 100%)`
- BackgroundOpacity: 20%

**Comment by pyk** [comment]
@ayikfour btw, I don't think we can do chart color on different mode. 

https://github.com/risedle/interface/blob/v1/components/v1/MarketDetailPage/LeveragedTokenChart.tsx#L113-L122

Currently the gradient is hardcoded

**Comment by ayikfour** [comment]
ohh got it, note it. I think we can go with the existing one then ✌️

**Comment by pyk** [comment]
Ok, let me close this first yea
