### ISSUE TITLE
Leveraged Token Market Detail Page: Use two columns on the desktop

### ISSUE THREAD

**Issue by pyk** [risedle/interface#107]
![Products](https://user-images.githubusercontent.com/2213646/152673714-eae67ef0-5d59-440a-b08e-397cc30491bc.png)

**Comment by ayikfour** [comment]
Update on the Interface design:
Time selection range on desktop version moved to the left, and have this specification for the width of each chip. 

Expected design:
![image](https://user-images.githubusercontent.com/28996086/153001365-de68e8b5-5b21-4d5c-bd36-3098424570d4.png)

**🔗 [Figma link for the design](https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=1358%3A42554)**

**Comment by pyk** [comment]
Fixed by #145
