### ISSUE TITLE
Product Detail Page (Leverage/Lend): Improvement in Return

### ISSUE THREAD

**Issue by ayikfour** [risedle/interface#111]
In the `Changes` section, **we add USD equals value**. In the current version, we just show the percentage. 

Here's the expected design:
![image](https://user-images.githubusercontent.com/28996086/152996336-745c17e1-741f-4dca-91c6-5279553894a9.png)

**Comment by ayikfour** [comment]
Updated the "My Asset" section

**Comment by pyk** [comment]
I will split this into two pull request:

1. Changes update
2. My Asset update

**Comment by pyk** [comment]
@ayikfour nav changes is live on production, please check.

 Can we create separate issue for the "My Asset" component?

so we can close this one

**Comment by ayikfour** [comment]
Thank you, already seen that on prod! ✌️

let me separate the issue for "My Asset" component
