### ISSUE TITLE
New Feature: Portfolio page

### ISSUE THREAD

**Issue by ayikfour** [risedle/interface#113]
Already provided the portfolio page design in Figma.
The data that will be shown are:
- Overall Asset
- The leverage token asset section
- The vault token asset section

Each asset will have this:
- Amount (how many tokens they hold)
- Value (how much the token is valued in USD
- Return (Shown in USD value)

Expected desktop:
![image](https://user-images.githubusercontent.com/28996086/152999799-f427d20a-6635-4dc8-9fdc-6a5a42e2da71.png)

**Design file:**
[Portfolio page design](https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=1406%3A42208)

**Comment by pyk** [comment]
Note about the implementation: We might fething transfer event directly from the ETHRISE contract address.

If transfer in to the user address, multiply the nav history with the amount and sum
If transfer out from the user address, multiply the nav history and minus previous total

**Comment by ayikfour** [comment]
Added transaction history section to Portfolio Page
Figma link: https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=1406%3A42208

**Comment by pyk** [comment]
@math-marcellino feel free to send your MR first. We have preview env now.

Environment:
preview -> Merged from MR, but not live on risedle.com
production -> Only merge from `preview` after its ok, live on risedle.com

Example live preview https://8cd69eab.frontend-3mt.pages.dev/

**Comment by ayikfour** [comment]
Merge this issue to Portfolio V2 #143
