### ISSUE TITLE
Design: Add button to trade ETHRISE on Uniswap

### ISSUE THREAD

**Issue by ayikfour** [risedle/interface#115]
Todo for designer based on user feedback on Discord channel
<img width="750" alt="image" src="https://user-images.githubusercontent.com/28996086/153362687-4d573895-5809-4c65-8d26-6f4bc7734e88.png">

**Comment by pyk** [comment]
@ayikfour btw is there any figma for this one?

**Comment by ayikfour** [comment]
Here's the link for "Buy on Uniswap" design ser https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=389%3A6866
