### ISSUE TITLE
Toast won't disappear

### ISSUE THREAD

**Issue by ayikfour** [risedle/interface#118]
When I'm interacting with an action that triggers a toast, the toast won't disappear until I reload the page. Is the duration already set up in the component?

<img width="449" alt="image" src="https://user-images.githubusercontent.com/28996086/153445380-b3a311fd-d77f-4751-a446-cb8f4dcd99ce.png">

**Comment by pyk** [comment]
Good catch, I think we need to add global duration in here:

https://github.com/risedle/interface/blob/v1/pages/_app.tsx#L11
