### ISSUE TITLE
UI Update: Popup/Dropdown menu

### ISSUE THREAD

**Issue by ayikfour** [risedle/interface#122]
Minor update for popup/dropdown menu component. The update:
- Rounded: adjusted to 8px
- States for Hover, Pressed, etc
- On desktop: Show menu on hover (current, user need to click it)

Design component can be seen here:
- https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=1546%3A52432

Prototype Playground: 
- https://www.figma.com/proto/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=486%3A18639&viewport=288%2C48%2C0.16&scaling=min-zoom&starting-point-node-id=797%3A29583&show-proto-sidebar=1

**Comment by asaadam** [comment]
i think this issue can be closed? 
@ayikfour

**Comment by ayikfour** [comment]
Yapyap, lets close this issue
