### ISSUE TITLE
UI Update: Product Icon

### ISSUE THREAD

**Issue by ayikfour** [risedle/interface#124]
Minor update, Product icon. Asset can be grabbed in here:
- https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=585%3A20439

**Comment by ayikfour** [comment]
Updated for rvUSDC icons in the Figma link

or you can grab the asset here in GDrive https://drive.google.com/drive/folders/1wDzxANGg9fw0V8VSRAhCkQPFfnnmxkYT?usp=sharing

**Comment by pyk** [comment]
@ayikfour oke deploying to prod

**Comment by ayikfour** [comment]
ty ser!

Btw got an issue, when opening in iOS Safari the icon is a bit blurry. 
Should we change to .png instead?

**Comment by pyk** [comment]
@ayikfour yes we can use .png instead of .svg. Let me update it

**Comment by pyk** [comment]
@ayikfour not sure why but if we use .png it will get very blurry (png is already exported in 2x size)

SVG
<img width="299" alt="Screen Shot 2022-02-19 at 18 30 52" src="https://user-images.githubusercontent.com/2213646/154799015-3bfc8a27-406f-4b2c-a21f-a803d01d4e63.png">

PNG
<img width="298" alt="Screen Shot 2022-02-19 at 18 30 58" src="https://user-images.githubusercontent.com/2213646/154799035-bca07e19-5da4-41f9-af50-4220a6fd13ae.png">

**Comment by pyk** [comment]
@ayikfour nvm, exporting it with 4x did the trick. It should works similar now on chrome and safari

**Comment by ayikfour** [comment]
Thank you ser!
