### ISSUE TITLE
Update: OG Image for /ETHRISE

### ISSUE THREAD

**Issue by ayikfour** [risedle/interface#126]
The existing open graph looks a bit flat. I try to make it more standout 🙂

The assets can be grabbed in here: https://drive.google.com/file/d/1E1VOSfb7BjM-pR7QiJk1276l7HOmY-du/view?usp=sharing

**Comment by pyk** [comment]
@ayikfour btw some minor changes here:

![Group 1](https://user-images.githubusercontent.com/2213646/154394659-e688d47e-362a-45f6-af82-1dad06bde50d.png)

1. "Without worries" -> "without worrying"
2. "2x ETH Leverage" -> "2x Long ETH"

**Comment by ayikfour** [comment]
Noted, let me change it

**Comment by ayikfour** [comment]
Updated ✌️
