### ISSUE TITLE
Bug : Missing dependency react-popper

### ISSUE THREAD

**Issue by asaadam** [risedle/interface#139]
react-popper was not defined on `package.json`, causing this error : 

![image](https://user-images.githubusercontent.com/1397612/158292854-06f8be69-f7e1-43c1-8c4d-675cfa45ea8a.png)

but strangely it's appears on `package-lock`
![image](https://user-images.githubusercontent.com/1397612/158292774-0bacf178-728e-463d-8dfb-983467ec7f50.png)

I assume someone was accidentally removing it's from `package.json`

**Comment by pyk** [comment]
Fixed by #140
