### ISSUE TITLE
Portfolio Page: Handle user not connected state

### ISSUE THREAD

**Issue by pyk** [risedle/interface#147]
We need to handle state when user access `/portfolio` but wallet is not connected yet

**Comment by pyk** [comment]
cc @ayikfour

**Comment by ayikfour** [comment]
Provided in here: https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=1862%3A87292

Nothing much changes from "Don't have portfolio" state. Just updated the copywritings. Wdyt?

**Comment by ayikfour** [comment]
Btw, can we close this issue? since it's already merged with issue #146

**Comment by pyk** [comment]
@ayikfour yess
