### ISSUE TITLE
Update docs icon

### ISSUE THREAD

**Issue by pyk** [risedle/interface#163]
Our docs is now hosted on Gitbook but the icon still use notion

<img width="397" alt="Screen Shot 2022-04-01 at 05 02 15" src="https://user-images.githubusercontent.com/2213646/161156635-3792674c-6f89-4043-a52c-7b2356c571af.png">

--

@ayikfour need to provide new icon then we can update it

**Comment by pyk** [comment]
We also need to update the mobile menu on the `/markets` page too

<img width="315" alt="Screen Shot 2022-04-01 at 05 18 02" src="https://user-images.githubusercontent.com/2213646/161158964-bb44a47d-f6ef-49cd-bc77-26bfdad98fbb.png">

**Comment by ayikfour** [comment]
Well noted ser

**Comment by ayikfour** [comment]
Updated docs icons.

Mobile menu: https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=2255%3A108836

Footer: https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=1791%3A150905

**Comment by pyk** [comment]
@ayikfour tysm!

**Comment by ayikfour** [comment]
Noprob mister!

**Comment by pyk** [comment]
Fixed by #193
