### ISSUE TITLE
[bug] Portfolio page: Incosistent placeholder text style dark mode vs light mode

### ISSUE THREAD

**Issue by pyk** [risedle/interface#168]
I think we need to add subtle background on the light mode

<img width="325" alt="Screen Shot 2022-04-01 at 05 35 02" src="https://user-images.githubusercontent.com/2213646/161161022-d5f25615-1cfd-4438-bfdb-b1c2937e4c61.png">
<img width="304" alt="Screen Shot 2022-04-01 at 05 35 38" src="https://user-images.githubusercontent.com/2213646/161161044-96a5f661-8f5e-4f58-bb1d-cbda1e92bfd9.png">

cc @ayikfour

**Comment by ayikfour** [comment]
![image](https://user-images.githubusercontent.com/28996086/161173375-f4f46667-6aba-45b5-9270-261e7626e4be.png)


I tried to recheck in the Figma. Actually we already have this in the design. Might be bug in the frontend(?)

**Comment by pyk** [comment]
@ayikfour yes, confirmed

**Comment by ayikfour** [comment]
Cool🙏

**Comment by pyk** [comment]
I think this is not relevant anymore, we use Temporary Portfolio for now
