### ISSUE TITLE
[bug] Update breakpoint for navigation

### ISSUE THREAD

**Issue by pyk** [risedle/interface#179]
<img width="723" alt="Screen Shot 2022-04-03 at 15 08 42" src="https://user-images.githubusercontent.com/2213646/161418474-0376ae20-5746-4289-a9bb-3ef3c3f6ce57.png">

The UI is breaking when viewport width is 640px-699px. I think we should use `md` instead of `sm`.

1. need to update the breakingpoint on navigation [this](https://github.com/risedle/interface/blob/preview/components/v1/Navigation.tsx#L42-L48)
2. need to update the [markets page](https://github.com/risedle/interface/blob/preview/components/v1/MarketsPage/MarketsPage.tsx#L192), [portfolio page](https://github.com/risedle/interface/blob/preview/components/v1/PortfolioPage/PortfolioPageV2.tsx#L268) and [market detail page](https://github.com/risedle/interface/blob/preview/components/v1/MarketDetailPage/ETHRISEPage.tsx#L200-L202)

**Comment by pyk** [comment]
<img width="939" alt="Screen Shot 2022-04-03 at 15 46 44" src="https://user-images.githubusercontent.com/2213646/161419685-b91838f2-086c-4466-9dc5-9d966de86058.png">
<img width="1014" alt="Screen Shot 2022-04-03 at 15 46 50" src="https://user-images.githubusercontent.com/2213646/161419686-b9915c8e-f4de-4081-9f67-279fcfac673a.png">

When the "Switch network" show up, it also break the UI

**Comment by pyk** [comment]
@ayikfour is it possible to align menus on left instead of center?

**Comment by ayikfour** [comment]
Ahhh i see, let's have it in the left ser. lemme update it

**Comment by ayikfour** [comment]
Updated the Layout for Navigation on Desktop https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=2289%3A115624

Move the Link Wrapper to left. Kindly check ser

**Comment by pyk** [comment]
Fixed by #194
