### ISSUE TITLE
[bug] Wrong network is not handled on portfolio

### ISSUE THREAD

**Issue by pyk** [risedle/interface#182]
<img width="1019" alt="Screen Shot 2022-04-03 at 15 40 54" src="https://user-images.githubusercontent.com/2213646/161419530-589d4213-6eda-4680-96d8-258212650637.png">

The portfolio valu sholdn't show up when user in the wrong network

**Comment by pyk** [comment]
Please see the figma here https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=2289%3A115239

Thanks @ayikfour :love:

**Comment by ayikfour** [comment]
You're welcome Ser!
