### ISSUE TITLE
Add meta image for portfolio page

### ISSUE THREAD

**Issue by pyk** [risedle/interface#185]
<img width="581" alt="Screen Shot 2022-04-03 at 19 24 15" src="https://user-images.githubusercontent.com/2213646/161427905-24f26381-962c-4dad-83fd-ec36bfbae17c.png">

cc @ayikfour

**Comment by ayikfour** [comment]
Provided here ser https://drive.google.com/file/d/1V03N-k2XK3BuPAVJu_AGX8MmIfwvrx1A/view?usp=sharing

**Comment by pyk** [comment]
Nice thanks!

**Comment by pyk** [comment]
Fixed by #193
