### ISSUE TITLE
New Mobile List Menu

### ISSUE THREAD

**Issue by asaadam** [risedle/interface#190]
currently 
![image](https://user-images.githubusercontent.com/1397612/161774425-3b3299c5-b088-44ca-a82d-c6fe2ce585be.png)

expected 
![image](https://user-images.githubusercontent.com/1397612/161774335-271f884e-7fb2-4e96-91bf-a6b4203810fc.png)

blue means active ( on current page )

**Comment by pyk** [comment]
Fixed by #191
